= The DC/OS (Datacenter Operating System)

:hp-tags: Datacenter

DC/OS or Datacenter Operating System is an open-source project started by a company named Mesosphere. The project aimed to make infrastructure blueprints (for building and delivering data-driven services to run on any datacenter or cloud) accessible for everyone.

It is a system that consists of Linux machines or nodes that communicate with one another, effectively sub-dividing large applications into small tasks that can be executed independently from one another in a more resource efficient manner. It is structured in such a way that each node performs a certain role. The roles these nodes can play include the master node, the private agent node, and the public agent node.

The _master node/s_ typically run a few services in the background (Zookeeper, Mesos, etc...) but generally are responsible for monitoring and making sure that the DC/OS cluster is in good condition, (by checking: the state of every node, running services or scheduled tasks, etc...), it reports any problems it identifies visualizable in the web UI homepage for DC/OS.

The _agent nodes_ are the workhorses for running services and applications. These agent nodes communicate their available resources to the master node and the master node being the orchestrator, devises a plan on how to carry out tasks with the resources these agent nodes expose and work toward combining their results. The master and agent nodes work together in an attempt to exploit and fully utilize the available resources agent nodes ( together as a whole) contribute as an offering to the cluster of master nodes.

This approach ensures that every task has dedicated resources making evaluations even more efficient, and effectively eliminating the problem of hardware limitations, typically seen when running an application on a single powerful machine.

After these tasks are evaluated, they are then communicated to a leader node (an elected master node that manages how and on which node tasks are running), that knows how to combine their outcomes and finish a cycle of what the application / service aimed to do.

https://docs.mesosphere.com/1.9/[DC/OS Documentation]

## Differentiating Apache Mesos, Mesosphere and DC/OS

*Mesos -* an open-source cluster resource manager, the Kernel of DC/OS.

*Mesosphere -* the company that started and continues to contribute to both Apache Mesos and DC/OS.

*DC/OS -* an open-source distribution around Apache Mesos including UI, networking, and many other pieces. Mesosphere also offers an Enterprise Edition of DC/OS with support and some advanced features.

https://stackoverflow.com/questions/44171100/whats-difference-between-apache-mesos-mesosphere-and-dcos[What's difference between Apache Mesos, Mesosphere and DCOS?]
Please *NOTE* the following:

* this setup is not intended for production use, but rather as a means for you to experience building an environment for sandboxing purposes.
* you will need to meet the minimum hardware requirements in order to fully experience the setup process for yourself.

https://github.com/dcos/dcos-vagrant/blob/master/[Github dcos-vagrant repository]

*Hardware requirements*

In terms of hardware, you should have at least *4GB available memory / RAM* and your operating system should be listed below:

*Operating System (OS)*

Mac OS X 10.x

Windows 7, 10

Ubuntu 14, 15, 16

Fedora 23

Arch Linux

*Software requirements*

For those already using a package manager, (i.e. Homebrew for the Mac, Linuxbrew for Linux, Scoop for Windows), please install the following components: `vagrant`,`VirtualBox`, and `git`.

If you don't have a package manager, you can always install the tools needed for this tutorial manually.

* https://git-scm.com/downloads[Git] a distributed version control system.
* https://www.vagrantup.com/downloads.html[Vagrant] a tool for building and managing virtual machine environments. It is recommended you install version 1.9.7 as previous versions appear to have issues.
* https://www.virtualbox.org/wiki/Downloads[VirtualBox] a cross-platform virtualization application.

If you haven't already done so, it would be good to start by first creating a working project directory and changing to that directory on a terminal.

Once in your working directory, run the following commands to clone the project repository and make it the current directory in your preferred command line tool.

[scala,source]

----
$ git clone https://github.com/dcos/dcos-vagrant

$ cd dcos-vagrant
----

## DC/OS setup guidelines

Install `vagrant-hostmanager`, a plugin that makes it possible for you to access virtual machines from your computer via ssh.

[scala,source]
----
$ vagrant plugin install vagrant-hostmanager
----

The following command populates your hosts file with the DNS routes to each of your cluster nodes.

[scala,source]
----
$ vagrant hostmanager
----

This next command appends to cluster configuration file a property that disables OAuth authentication for your DC/OS cluster.















